export const GET_WEB3OBJECTS_START = 'GET_WEB3OBJECTS_START';
export const GET_WEB3OBJECTS_SUCCESS = 'GET_WEB3OBJECTS_SUCCESS';
export const GET_WEB3OBJECTS_FAIL = 'GET_WEB3OBJECTS_FAIL';

export const FETCH_ADDRESSINFO_START = 'FETCH_ADDRESSINFO_START';
export const FETCH_ADDRESSINFO_SUCCESS = 'FETCH_ADDRESSINFO_SUCCESS';
export const FETCH_ADDRESSINFO_FAIL = 'FETCH_ADDRESSINFO_FAIL';

export const GET_IPFS_START = 'GET_IPFS_START';
export const GET_IPFS_SUCCESS = 'GET_IPFS_SUCCESS';
export const GET_IPFS_FAIL = 'GET_IPFS_FAIL';

export const CREATE_ARTWORK_START = 'CREATE_ARTWORK_START';
export const CREATE_ARTWORK_SUCCESS = 'CREATE_ARTWORK_SUCCESS';
export const CREATE_ARTWORK_FAIL = 'CREATE_ARTWORK_FAIL';

export const SUPPORT_ARTWORK_START = 'SUPPORT_ARTWORK_START';
export const SUPPORT_ARTWORK_SUCCESS = 'SUPPORT_ARTWORK_SUCCESS';
export const SUPPORT_ARTWORK_FAIL = 'SUPPORT_ARTWORK_FAIL';
export const CLEAR_SUPPORT_STATE = 'CLEAR_SUPPORT_STATE';

export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';

export const FOLLOW_USER_START = 'FOLLOW_USER_START';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL';

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';